version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=subscription_manager_user
      - POSTGRES_DB=subscription_manager_test
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: